---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

options(java.parameters = "-Xmx20G")
Sys.setenv(JAVA_HOME="D:/Program Files/jdk-11")

library(checkpoint)
library(tidyverse)
library(knitr)
library(sf)
library(sp)
library(raster)
library(spdep)
library(purrr)
library(lme4)
library(jtools)
library(merTools)
library(spgwr)
library(interflex)
library(stargazer)
library(devtools)
library(tidyr)
library(expss)
library(MatchIt)
library(broom)
library(rgenoud)
library(nngeo)
library(ineq)
library(lctools)
library(DescTools)
library(fs)
library(stringr)
#library(dbplyr)
library(matrixStats)
library(seg)
library(acid)
library(reldist)
library(dineq)
library(laeken)
library(RColorBrewer)
library(hrbrthemes)
library(ggmap)
library(gridExtra)
library(osmdata)
library(viridis)
library(foreign)
library(weights)
library(splitstackshape)
library(ergm)
library(cowplot)
library(rgdal)
library(matchingR)
library(rlist)
library(lpSolve)
library(geosphere)
library(link2GI)
#library(nnetpredint)
library(rgeos)
library(rgrass7)
library(shp2graph)
library(reshape2)
library(biscale)
library(SpatialPosition)
library(rJava)
library(Hmisc)
#library(osmar)
library(tidygraph)
library(igraph)
library(r5r)
library(elevatr)
library(leaflet)
library(reticulate)
library(read.dbc)
library(ggnewscale)
library(janitor)
library(rmapshaper)
library(DescTools)
library(Hmisc)
library(corrplot)
library(GGally)

mutate <- dplyr::mutate
select <- dplyr::select
filter <- dplyr::filter
rename <- dplyr::rename
distinct <- dplyr::distinct
pull <- dplyr::pull
summarize <- dplyr::summarize
nest <- tidyr::nest

sf::sf_use_s2(FALSE)

weighted.ttest.ci <- function(x, weights, conf.level = 0.95) {
  a <- tibble(x,weights) %>% na.omit() %>%
    filter(is.finite(x)) %>% filter(is.finite(weights))
  x <- a$x
  weights <- a$weights
  nx <- length(x)
  df <- nx - 1
  vx <- Hmisc::wtd.var(x, weights, normwt = TRUE) ## From Hmisc
  mx <- weighted.mean(x, weights)
  stderr <- sqrt(vx/nx)
  tstat <- mx/stderr ## not mx - mu
  alpha <- 1 - conf.level
  cint <- qt(1 - alpha/2, df)
  cint <- tstat + c(-cint, cint)
  c(cint * stderr,mx)
}

is_outlier <- function(x) {
  return(x < quantile(x, 0.25) - 1.5 * IQR(x) | x > quantile(x, 0.75) + 1.5 * IQR(x))
}

diffRound <- function(x) { 
  diff(c(0, round(cumsum(x)))) 
}

```

# São Paulo

```{r maps_functions_sp}

  mun <- st_read(paste0("sp_mun_MR.shp"))
  mun_city <- st_read(paste0("sp_mun.shp"))
  mask <- st_read(paste0("sp_cover_MR.shp"))
  back <- st_read("br_mun.shp")

# Base theme map
theme_map <- function(...){
  theme(
    axis.line = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "#f0f0f0", color = NA),
    plot.title = element_blank(),
    plot.subtitle = element_blank(),
    legend.title = element_text(size = 12, color = "#4e4d47",family="Helvetica"),
    legend.text = element_text(size = 10, hjust = 0, color = "#4e4d47",family="Helvetica"),
    legend.background = element_rect(fill = alpha('white', 0.5)),
    #legend.key = element_rect(color = NA, fill = NA),
    legend.key.size = unit(12, "cm"),
    ...)}

# Bivariate maps
PlotMap3 <- function(base,variable,name_var,variable2,name_var2) {
  
  zoom_x <- c(-46.85,-46.35)
  zoom_y <- c(-23.9,-23.4)
  bar_scale <- 7.5
  pos_legend <- c(0.75,0.25)
  
  breaks <- c(0,5,10,15,20,25,30,1000)
  #breaks <- c(0,10,20,30,40,50,60,10000)
  base$breaks <- cut(variable,breaks = breaks,include.lowest = TRUE,labels = breaks[2:8])
  breaks_scale <- levels(base$breaks) %>% as.numeric()
  labels <- c(paste0(breaks[2:7]," min."),"> 30 min.")
  
  breaks2 <- c(0,10,50,100,200,400,600,1000000)
  base$breaks2 <- cut(variable2,breaks = breaks2,include.lowest = TRUE,labels = breaks2[2:8])
  breaks_scale2 <- levels(base$breaks2) %>% as.numeric()
  labels2 <- c(paste0(breaks2[2:7]," people"),"> 600 people")
  
  # Plot map
  map <- ggplot() +
    geom_sf(data = back %>% filter(DN == "0"), mapping = aes(), fill = "#f0f0f0", size = 0.3, color = "white") +
    theme_map() +
    theme(legend.position = pos_legend) + 
    #geom_sf(data = hex,mapping=aes(),fill = "#C5C5C5",color = NA) +
    
    geom_sf(data = base, aes(fill = breaks), color = NA)  +
    scale_fill_manual(
      values = cols,
      breaks = rev(breaks_scale),
      name = name_var,
      drop = FALSE,
      labels = rev(labels),
      na.value = "transparent",
      guide = guide_legend(
        #direction = "vertical",
        keyheight = unit(3, units = "mm"),
        keywidth = unit(7, units = "mm"),
        title.position = 'top',
        #title.hjust = 0.5,
        #label.hjust = 1,
        #nrow = 1,
        #byrow = T,
        reverse = T,
        label.position = "right")) +
    
    new_scale_fill() +
    
    geom_sf(data=base, aes(fill = breaks2,alpha = breaks2),color=NA) +
    
    scale_fill_manual(
      values = cols2,
      breaks = rev(breaks_scale2),
      name = name_var2,
      drop = FALSE,
      labels = rev(labels2),
      na.value = "transparent",
      guide = guide_legend(
        #direction = "vertical",
        keyheight = unit(3, units = "mm"),
        keywidth = unit(7, units = "mm"),
        title.position = 'top',
        #title.hjust = 0.5,
        #label.hjust = 1,
        #nrow = 1,
        #byrow = T,
        reverse = T,
        label.position = "right")) +
    
    scale_alpha_manual(
      values = c(0,0.2,0.4,0.8,0.8,1,1),
      guide='none') +
    
    geom_sf(data = mask %>% filter(DN != 3), mapping = aes(), fill = "white", color = NA) +
    geom_sf(data = mun_city %>% summarise(), mapping = aes(), fill = "transparent", color = "white", size = 0.7) +
    #geom_sf(data = transport, mapping = aes(), color = "#606060", size = 0.5,linetype = "dashed") +
    coord_sf(xlim=zoom_x,ylim=zoom_y) +
    ggsn::scalebar(data = mun_city, dist = bar_scale, st.color = "#4e4d47", st.size=2, box.fill = c("#4e4d47","#f0f0f0"), box.color = "#4e4d47", border.size = 0.2, height=0.015, dist_unit = "km", location = "bottomleft", model = 'WGS84',transform = TRUE, anchor = c(x=zoom_x[1], y=zoom_y[1])) +
    ggsn::north(data = mun_city, location = "topright", scale = 0.1, symbol = 6, anchor = c(x=zoom_x[2], y=zoom_y[2]))
  
  return(map)
}

```

```{r census_data_sp}

grid <- st_read("sp_grid_data500.shp")

grid <- grid %>%
  mutate(id = as.numeric(id)) %>%
  arrange(id) %>%
  filter(round(pop) > 0)
  
```

```{r matrix_WALK}

#elevat <- get_elev_raster(grid,z=14)
#writeRaster(elevat,"sp/elevation_sp.tiff")

options(java.parameters = "-Xmx20G")
Sys.setenv(JAVA_HOME="D:/Program Files/jdk-11")

origin <- grid %>%
  st_centroid() %>%
  st_coordinates() %>%
  as_tibble() %>%
  cbind(GEO_ID = grid$id) %>%
  select(GEO_ID,X,Y) %>%
  mutate(GEO_ID = as.numeric(GEO_ID)) %>%
  arrange(GEO_ID)
colnames(origin) <- c("id","lon","lat")

r5r_core <- setup_r5(data_path = "SP", verbose = FALSE)
mode <- c("WALK")
max_walk_dist <- 100000
max_trip_duration <- 6*60
departure_datetime <- as.POSIXct("19-03-2020 07:00:00",
                                 format = "%d-%m-%Y %H:%M:%S")

no_access <- NULL

```

```{r todos}

hiper <- st_read("Hipers_estat_descritiva.gpkg") %>% bind_rows(st_read("Hortifrutis_estat_descritiva.gpkg"))%>% bind_rows(st_read("Minis_estat_descritiva.gpkg"))%>% bind_rows(st_read("Supers_estat_descritiva.gpkg")) %>%
  mutate(ID = row_number())%>%
  st_drop_geometry() %>%
  filter(!is.na(lat)) %>%
  filter(!is.na(long)) %>%
  mutate_at(c("lat","long"),as.numeric)
hiper <- hiper[!duplicated(hiper),]

hiper <- st_read("dbscan200.shp") %>%
  st_drop_geometry() %>%
  group_by(CLUSTER_ID) %>%
  summarise(lat = mean(lat,na.rm=T),
            long = mean(long,na.rm=T),
            capacidade_pessoas = sum(as.numeric(capacidade),na.rm=T)) %>%
  rename("ID" = CLUSTER_ID)
sum(hiper$capacidade_pessoas)

destination <- hiper %>%
  select(ID,capacidade_pessoas,lat,long) %>%
  filter(capacidade_pessoas > 0) %>%
  st_as_sf(coords=c("long","lat")) %>%
  st_set_crs(4326)

destination %>%
  ggplot() +
  geom_sf(aes(color=capacidade_pessoas))

destination <- destination %>%
  ungroup() %>%
  mutate(lon = st_coordinates(destination)[,1],
         lat = st_coordinates(destination)[,2]) %>%
  st_drop_geometry() %>%
  select(ID,lon,lat) %>%
  arrange(ID)
colnames(destination) <- c("id","lon","lat")

# calculate a travel time matrix
ttm <- travel_time_matrix(r5r_core = r5r_core,
                          origins = origin,
                          destinations = destination,
                          mode = mode,
                          departure_datetime = departure_datetime,
                          #max_walk_dist = max_walk_dist,
                          max_trip_duration = max_trip_duration,
                          verbose = FALSE)

head(ttm)
saveRDS(ttm,"outputs/ttm_sp500_dbscan200.rds")
ttm <- readRDS("outputs/ttm_sp500_dbscan200.rds")

#### OBT ####

grid <- grid %>%
  filter(pop > 0) %>%
  mutate(id = as.numeric(id)) %>%
  arrange(id)
destination <- destination %>%
  left_join(hiper %>%
  ungroup() %>%
  filter(capacidade_pessoas > 0) %>%
  select(ID,capacidade_pessoas),by=c("id"="ID"))%>%
  mutate(id = as.numeric(id)) %>%
  arrange(id) 

# Population (supply)
  #pop <- round(grid$pop)
  #row.signs <- rep("<=",length(pop))
  #row.rhs <- round(grid$pop)
  #n_pop <- sum(pop)
  
  # Opportunities (demand)
  #opp <- round(destination$capacidade_pessoas)
  #col.signs <- rep(">=",length(opp))
  #col.rhs <- round(destination$capacidade_pessoas)
  #n_opp <- sum(opp)
  
  # Population (supply)
  pop <- round(grid$pop/10)
  col.signs <- rep("<=",length(pop))
  col.rhs <- round(grid$pop/10)
  n_pop <- sum(pop)
  
  # Opportunities (demand)
  opp <- round(destination$capacidade_pessoas/10)
  row.signs <- rep(">=",length(opp))
  row.rhs <- round(destination$capacidade_pessoas/10)
  n_opp <- sum(opp)
  
  matrix <- tibble(from_id = rep(unique(origin$id),length(unique(destination$id))),
                   to_id = rep(unique(destination$id),each=length(unique(origin$id)))) %>%
    mutate_at(c("from_id","to_id"),as.numeric) %>%
    left_join(ttm %>%
    mutate_at(c("from_id","to_id"),as.numeric),by=c("from_id","to_id")) %>%
    arrange(from_id,to_id)
  matrix[is.na(matrix)] = 100000 
  
  matrix <- matrix %>%
    spread(key="to_id",value="travel_time_p50") %>%
    column_to_rownames("from_id") %>%
    as.matrix() 
  
  matrix <- matrix %>% t()
  
# OBT
solution <- lp.transport(cost.mat = matrix,
                         direction = "min",
                         row.signs = row.signs,
                         row.rhs = row.rhs,
                         col.signs = col.signs,
                         col.rhs = col.rhs)
solution
solution %>% saveRDS("outputs/solution_sp500_dbscan200.rds")
solution <- readRDS("outputs/solution_sp500_dbscan200.rds")

access <- solution$solution %>%
  as_tibble() 
colnames(access) <- destination$id

#access <- access %>%
#  mutate(from_id = origin$id) %>%
#  gather(key = "to_id",value = "match",-c(from_id)) %>%
#  mutate_at(c("from_id","to_id"),as.numeric) 

access <- access %>%
  mutate(from_id = destination$id) %>%
  gather(key = "to_id",value = "match",-c(from_id)) %>%
  mutate_at(c("from_id","to_id"),as.numeric) 

sum(access$match)
sum(opp)

#match_opp <- access %>%
#  filter(match > 0) %>%
#  left_join(grid %>% st_drop_geometry(),by=c("from_id"="id")) %>%
#  left_join(hiper,by=c("to_id"="ID")) %>%
#  select("from_id","pop","to_id","capacidade_pessoas","match")

match_opp <- access %>%
  filter(match > 0) %>%
  left_join(hiper %>% st_drop_geometry(),by=c("from_id"="ID")) %>%
  left_join(grid,by=c("to_id"="id")) %>%
  select("from_id","pop","to_id","capacidade_pessoas","match")

aux_desag <- access %>%
  left_join(ttm %>%
  mutate_at(c("from_id","to_id"),as.numeric),by=c("from_id","to_id")) %>%
  ungroup() %>%
  left_join(hiper,by=c("to_id"="ID")) %>%
  filter(match > 0)

access <- access %>%
  left_join(ttm %>%
  mutate_at(c("from_id","to_id"),as.numeric),by=c("from_id","to_id")) %>%
  ungroup() %>%
  group_by(from_id) %>%
  summarise(travel_time=stats::weighted.mean(travel_time_p50,match,na.rm=T),
            match = sum(match,na.rm=T))
access$travel_time[is.nan(access$travel_time)] <- NA

access <- grid %>%
  left_join(access,by=c("id"="from_id")) %>%
  mutate(no_match = round(pop)-match,
         no_match_pct = (round(pop)-match)/pop) %>%
  mutate(travel_time_final = travel_time) %>%
  mutate(travel_time_final = ifelse(no_match > 0.5,5000,travel_time_final))
  
  name_var <- "Tempo até o\nhipermercado mais próximo"
  name_var2 <- "Pessoas sem acesso\na hipermercados"
  plot <- PlotMap3(access,access$travel_time,name_var,access$no_match,name_var2)
  plot
  ggsave("sp_hiper_biv.png",plot,device = "png",path = "OBT/outputs/",dpi = 600,width=7,height = 7)

```
